### ISSUE TITLE
@micropython.asm_thumb code fails with an internal sim error

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/micropython-microbit-v2-simulator#81]
E.g.
```python
@micropython.asm_thumb
def asm_add(r0, r1):
    add(r0, r0, r1)

print(asm_add(1, 2))
```

Results in:

```
instrument.ts:109 RuntimeError: table index is out of bounds
    at 004b255a
    at 004b255a
    at 004b255a
    at ret.<computed> (firmware.js:1948:35)
    at firmware.js:1045:22
    at invoke_iiiii (firmware.js:2459:12)
    at imports.<computed> (firmware.js:1914:35)
    at 004b255a
    at 004b255a
    at 004b255a
```

Ideally we'd fail cleanly saying it wasn't supported but only when the relevant code is run.

**Comment by microbit-matt-hillsdon** [comment]
Note the editor also lacks support, see https://github.com/microbit-foundation/python-editor-v3/issues/774

**Comment by microbit-matt-hillsdon** [comment]
Discussed with @dpgeorge today and he'll respond here.

**Comment by dpgeorge** [comment]
You can use:
```c
#define MICROPY_EMIT_INLINE_THUMB               (0)
```
to totally disable this feature.

Or try this to make it raise an exception just before executing the asm-thumb code:
```c
#define MICROPY_MAKE_POINTER_CALLABLE(p) \
    (mp_raise_msg(&mp_type_RuntimeError, MP_ERROR_TEXT("asm_thumb code not supported"))), p
```
